<?xml version="1.0" encoding="utf-8"?><Database Name="RedTelephone" Class="ModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NICK-C\SQLEXPRESS;Initial Catalog=RedTelephone;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RedTelephoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_CDFUSR" Member="Users">
    <Type Name="User">
      <Column Name="E_USRUIDC" Member="userName" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_USRUPWE" Member="hashCombo" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRUNFE" Member="firstName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRUNLE" Member="lastName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRIACT" Member="active_p" Type="System.String" DbType="char(1)" CanBeNull="false" />
      <Association Name="User_UserPermissionPair" Member="UserPermissionPairs" ThisKey="userName" OtherKey="userName" Type="UserPermissionPair" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFPNM" Member="Permissions">
    <Type Name="Permission">
      <Column Name="E_PNMCODC" Member="permission" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_PNMDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_PNMSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFUPM" Member="UserPermissionPairs">
    <Type Name="UserPermissionPair">
      <Column Name="E_UPMPNMC" Member="permission" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_USRUIDC" Member="userName" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_UserPermissionPair" Member="User" ThisKey="userName" OtherKey="userName" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFPRI" Member="Priorities">
    <Type Name="Priority">
      <Column Name="E_PRICODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_PRIDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_PRISEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_PRIIACT" Member="active_p" Type="System.String" DbType="char(1)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFTOT" Member="ReferenceTables">
    <Type Name="ReferenceTable">
      <Column Name="E_TOTTNMC" Member="name" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_RORMDTC" Member="lastUpdate" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFSRT" Member="TicketSources">
    <Type Name="TicketSource">
      <Column Name="E_SRTCODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRTDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_SRTSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_SRTIACT" Member="active_p" Type="System.String" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFSTS" Member="Status">
    <Type Name="Status">
      <Column Name="E_STSCODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_STSDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_STSSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_STSIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFCAP" Member="Causes">
    <Type Name="Cause">
      <Column Name="E_CAPCODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CAPDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_CAPSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_CAPIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFSRP1" Member="IssueSourceLvl1s">
    <Type Name="IssueSourceLvl1">
      <Column Name="E_SRP1CODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP1DSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP1SEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP1IACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFSRP2" Member="IssueSourceLvl2s">
    <Type Name="IssueSourceLvl2">
      <Column Name="E_SRP1CODC" Member="parentCode" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP2CODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP2DSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP2SEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP2IACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFSRP3" Member="IssueSourceLvl3s">
    <Type Name="IssueSourceLvl3">
      <Column Name="E_SRP1CODC" Member="grandparentCode" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP2CODC" Member="parentCode" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP3CODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_SRP3DSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP3SEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_SRP3IACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFRRM" Member="RequestedResponses">
    <Type Name="RequestedResponse">
      <Column Name="E_RRMCODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_RRMDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_RRMSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_RRMIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFRAM" Member="ActualResponses">
    <Type Name="ActualResponse">
      <Column Name="E_RAMCODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_RAMDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_RAMSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_RAMIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFCTT" Member="Contracts">
    <Type Name="Contract">
      <Column Name="E_CTTCIDC" Member="code" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CTTCNAM" Member="description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="E_CTTSEQC" Member="sortIndex" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_CTTIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.E_CDFCMP" Member="Companies">
    <Type Name="Company">
      <Column Name="E_CMPCIDC" Member="contractCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CMPPIDC" Member="code" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CMPCNAM" Member="description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="E_CMPSEQC" Member="sortIndex" Type="System.Int32" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_CMPIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFOFF" Member="Offices">
    <Type Name="Office">
      <Column Name="E_OFFCIDC" Member="contractCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_OFFPIDC" Member="companyCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_OFFIDT" Member="code" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_OFFVNE" Member="version" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_OFFNAM" Member="description" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="E_OFFSEQC" Member="sortIndex" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_OFFIACT" Member="active_p" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFCEE" Member="Employees">
    <Type Name="Employee">
      <Column Name="E_CEECIDC" Member="contractCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CEEPIDC" Member="companyCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CEEEIDT" Member="code" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CEEEVNE" Member="version" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_CEEEFNM" Member="firstName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="E_CEEEFLM" Member="lastName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="E_CEESEQC" Member="sortIndex" Type="System.Int32" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_CEEIACT" Member="active_p" Type="System.String" DbType="char(1)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFTKT" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="E_TKTTIDC" Member="code" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_TKTTVNE" Member="version" Type="System.Int32" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTCIDC" Member="contractCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTPIDC" Member="companyCode" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTFIDT" Member="officeCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTFVNE" Member="officeVersion" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTEIDT" Member="employeeCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTEVNE" Member="employeeVersion" Type="System.Int32" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTPRIC" Member="priorityCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSRTC" Member="ticketSourceCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSROE" Member="ticketSourceAlt" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSC1C" Member="issueSourceLvl1Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSC2C" Member="issueSourceLvl2Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSC3C" Member="issueSourceLvl3Code" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTRRMC" Member="requestedResponseCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSTSC" Member="statusCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTCAUC" Member="causeCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTAMC" Member="actualResponseCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTUIEC" Member="enteringUserName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTDTEE" Member="enteringTime" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTUIAC" Member="assignedUserName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTDTAE" Member="solvedTime" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTUIRC" Member="respondingUserName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTDTRE" Member="respondingTime" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTUIUC" Member="updatingUserName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTDTUE" Member="updatingTime" Type="System.String" DbType="Char(14) NOT NULL" CanBeNull="false" />
      <Column Name="E_TKTSCOE" Member="issueSourceAlt" Type="System.String" DbType="varchar(32)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFNOT" Member="TicketNotes">
    <Type Name="TicketNote">
      <Column Name="E_NOTTIDC" Member="code" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_NOTNTPC" Member="type" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_NOTSEQC" Member="sortIndex" Type="System.Int32" DbType="Decimal(3,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_NOTTXTE" Member="content" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="E_NOTUIEC" Member="enteringUserName" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>