<?xml version="1.0" encoding="utf-8"?><Database Name="RedTelephone" Class="ModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NICK-C\SQLEXPRESS;Initial Catalog=RedTelephone;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RedTelephoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_CDFUSR" Member="Users">
    <Type Name="User">
      <Column Name="E_USRUIDC" Member="userName" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_USRUPWE" Member="hashCombo" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRUNFE" Member="firstName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRUNLE" Member="lastName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="E_USRIACT" Member="active_p" Type="System.String" DbType="char(1)" CanBeNull="false" />
      <Association Name="User_UserPermissionPair" Member="UserPermissionPairs" ThisKey="userName" OtherKey="userName" Type="UserPermissionPair" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFPNM" Member="Permissions">
    <Type Name="Permission">
      <Column Name="E_PNMCODC" Member="permission" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_PNMDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_PNMSEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_CDFUPM" Member="UserPermissionPairs">
    <Type Name="UserPermissionPair">
      <Column Name="E_UPMPNMC" Member="permission" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_USRUIDC" Member="userName" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_UserPermissionPair" Member="User" ThisKey="userName" OtherKey="userName" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_CRFPRI" Member="Priorities">
    <Type Name="Priority">
      <Column Name="E_PRICODC" Member="code" Type="System.String" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_PRIDSCE" Member="description" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="E_PRISEQC" Member="sortIndex" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="E_PRIIACT" Member="active_p" Type="System.String" DbType="char(1)" CanBeNull="false" />
    </Type>
  </Table>
</Database>